-- 0001.baseline-schema  (dialeto PostgreSQL)
-- Estado consolidado do schema: tabelas + índices + views.
-- Convergente (CREATE TABLE IF NOT EXISTS / CREATE OR REPLACE VIEW): seguro rodar
-- num banco vazio. Tabelas em ordem de dependência (sem desabilitar FK check).
--
-- Migrado de MySQL 8 para PostgreSQL 16 na issue #115. As 3 views de cálculo
-- pesado (v_gmd_analitico, v_fluxo_caixa, vw_resultado_lote) viram MATERIALIZED
-- VIEW na 0003 — aqui ficam como view normal para o CREATE ser convergente.
-- Política só-aditiva de schema (#78): migrações seguintes nunca dão DROP.

CREATE TABLE IF NOT EXISTS usuarios (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      varchar(50)  NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    email         varchar(255) UNIQUE,
    created_at    timestamptz  DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lotes (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            integer NOT NULL REFERENCES usuarios(id),
    codigo_lote        varchar(50)  NOT NULL,
    descricao          varchar(200),
    data_aquisicao     date NOT NULL,
    custo_medio_cabeca numeric(10,2),
    created_at         timestamptz DEFAULT now(),
    deleted_at         timestamptz
);
CREATE INDEX IF NOT EXISTS idx_lotes_user ON lotes (user_id);

CREATE TABLE IF NOT EXISTS animais (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brinco          varchar(50) NOT NULL,
    sexo            char(1) NOT NULL,
    raca            varchar(100),
    data_compra     date,
    preco_compra    numeric(10,2),
    data_venda      date,
    preco_venda     numeric(10,2),
    user_id         integer NOT NULL REFERENCES usuarios(id),
    deleted_at      timestamptz,
    lote_id         integer REFERENCES lotes(id),
    pai_id          integer REFERENCES animais(id) ON DELETE SET NULL,
    mae_id          integer REFERENCES animais(id) ON DELETE SET NULL,
    data_nascimento date,
    UNIQUE (brinco, user_id)
);
CREATE INDEX IF NOT EXISTS idx_animais_venda        ON animais (user_id, data_venda);
CREATE INDEX IF NOT EXISTS idx_animais_ativo        ON animais (user_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_animais_ativo_venda  ON animais (user_id, deleted_at, data_venda);
CREATE INDEX IF NOT EXISTS idx_animais_brinco       ON animais (user_id, deleted_at, brinco);
CREATE INDEX IF NOT EXISTS idx_animais_lote         ON animais (lote_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_animais_raca         ON animais (user_id, raca, deleted_at);
CREATE INDEX IF NOT EXISTS idx_animais_pai          ON animais (pai_id);
CREATE INDEX IF NOT EXISTS idx_animais_mae          ON animais (mae_id);

CREATE TABLE IF NOT EXISTS pesagens (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id    integer NOT NULL REFERENCES animais(id),
    data_pesagem date NOT NULL,
    peso         numeric(10,2) NOT NULL,
    deleted_at   timestamptz
);
CREATE INDEX IF NOT EXISTS idx_pesagens_otimizada ON pesagens (animal_id, data_pesagem);
CREATE INDEX IF NOT EXISTS idx_pesagens_max       ON pesagens (animal_id, id DESC);

CREATE TABLE IF NOT EXISTS medicacoes (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id        integer NOT NULL REFERENCES animais(id),
    data_aplicacao   date NOT NULL,
    nome_medicamento varchar(100) NOT NULL,
    custo            numeric(10,2),
    observacoes      text,
    deleted_at       timestamptz
);
CREATE INDEX IF NOT EXISTS idx_med_busca ON medicacoes (animal_id, data_aplicacao);

CREATE TABLE IF NOT EXISTS custos_operacionais (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES usuarios(id),
    categoria   varchar(20) NOT NULL,
    tipo_custo  varchar(50) NOT NULL,
    valor       numeric(10,2) NOT NULL,
    data_custo  date NOT NULL,
    descricao   text,
    deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS idx_custos_busca          ON custos_operacionais (user_id, data_custo);
CREATE INDEX IF NOT EXISTS idx_custos_user_del_data  ON custos_operacionais (user_id, deleted_at, data_custo);

CREATE TABLE IF NOT EXISTS configuracoes (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL UNIQUE REFERENCES usuarios(id),
    nome_fazenda  varchar(100),
    cidade_estado varchar(100),
    area_total    numeric(10,2),
    gmd_meta      numeric(5,3) NOT NULL DEFAULT 0.800
);

CREATE TABLE IF NOT EXISTS financial_schedule (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL REFERENCES usuarios(id),
    descricao   varchar(255) NOT NULL,
    valor       numeric(10,2) NOT NULL,
    vencimento  date NOT NULL,
    status      varchar(20) DEFAULT 'pendente',
    created_at  timestamptz DEFAULT now(),
    deleted_at  timestamptz
);
CREATE INDEX IF NOT EXISTS idx_financial_schedule_agenda ON financial_schedule (user_id, deleted_at, vencimento);

CREATE TABLE IF NOT EXISTS cost_centers (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      varchar(50) NOT NULL,
    categoria varchar(20) NOT NULL,
    UNIQUE (nome, categoria)
);

CREATE TABLE IF NOT EXISTS pastos (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nome          varchar(100) NOT NULL,
    area_hectares numeric(10,2),
    forrageira    varchar(100),
    capacidade_ua numeric(10,2),
    created_at    timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pastos_user ON pastos (user_id);

CREATE TABLE IF NOT EXISTS modulos (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pasto_id      integer NOT NULL REFERENCES pastos(id) ON DELETE CASCADE,
    user_id       integer NOT NULL REFERENCES usuarios(id),
    nome          varchar(100) NOT NULL,
    area_hectares numeric(10,2),
    capacidade_ua numeric(10,2),
    created_at    timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_modulos_user  ON modulos (user_id);
CREATE INDEX IF NOT EXISTS idx_modulos_pasto ON modulos (pasto_id);

CREATE TABLE IF NOT EXISTS ocupacoes (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modulo_id    integer NOT NULL REFERENCES modulos(id) ON DELETE CASCADE,
    user_id      integer NOT NULL REFERENCES usuarios(id),
    data_entrada date NOT NULL,
    data_saida   date,
    created_at   timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ocupacoes_user   ON ocupacoes (user_id);
CREATE INDEX IF NOT EXISTS idx_ocupacoes_modulo ON ocupacoes (modulo_id);

CREATE TABLE IF NOT EXISTS ocupacao_animais (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ocupacao_id integer NOT NULL REFERENCES ocupacoes(id) ON DELETE CASCADE,
    animal_id   integer NOT NULL REFERENCES animais(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ocupacao_animais_animal ON ocupacao_animais (animal_id);
CREATE INDEX IF NOT EXISTS idx_ocupacao_animais_oc     ON ocupacao_animais (ocupacao_id);

CREATE TABLE IF NOT EXISTS reproducao (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaca_id             integer NOT NULL REFERENCES animais(id) ON DELETE CASCADE,
    touro_id            integer REFERENCES animais(id) ON DELETE SET NULL,
    touro_externo       varchar(200),
    data_cobertura      date NOT NULL,
    diagnostico         varchar(10) DEFAULT 'pendente' CHECK (diagnostico IN ('pendente','positivo','negativo')),
    data_diagnostico    date,
    data_parto_prevista date,
    data_parto          date,
    resultado           varchar(10) NOT NULL CHECK (resultado IN ('vivo','natimorto','aborto')),
    user_id             integer NOT NULL REFERENCES usuarios(id),
    created_at          timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_reproducao_touro ON reproducao (touro_id);
CREATE INDEX IF NOT EXISTS idx_reproducao_vaca  ON reproducao (vaca_id);
CREATE INDEX IF NOT EXISTS idx_reproducao_user  ON reproducao (user_id, data_parto_prevista);

CREATE TABLE IF NOT EXISTS estoque_produtos (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nome            varchar(200) NOT NULL,
    unidade         varchar(50) NOT NULL,
    categoria       varchar(20) NOT NULL DEFAULT 'outro'
                    CHECK (categoria IN ('medicamento','vacina','suplemento','mineral','outro')),
    estoque_minimo  numeric(10,3) NOT NULL DEFAULT 0.000,
    created_at      timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_estoque_produtos_user ON estoque_produtos (user_id);

CREATE TABLE IF NOT EXISTS estoque_movimentacoes (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL REFERENCES usuarios(id),
    produto_id      integer NOT NULL REFERENCES estoque_produtos(id) ON DELETE CASCADE,
    tipo            varchar(10) NOT NULL CHECK (tipo IN ('entrada','saida')),
    quantidade      numeric(10,3) NOT NULL,
    custo_unitario  numeric(10,2),
    motivo          varchar(300),
    lote_fabricante varchar(100),
    data_validade   date,
    data_mov        date NOT NULL,
    created_at      timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_estoque_mov_user    ON estoque_movimentacoes (user_id);
CREATE INDEX IF NOT EXISTS idx_estoque_mov_produto ON estoque_movimentacoes (produto_id, user_id);

CREATE TABLE IF NOT EXISTS protocolos_sanitarios (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nome              varchar(200) NOT NULL,
    descricao         text,
    intervalo_dias    integer NOT NULL,
    proxima_aplicacao date NOT NULL,
    ativo             smallint DEFAULT 1,
    created_at        timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sanitario_agenda ON protocolos_sanitarios (user_id, proxima_aplicacao, ativo);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    code       char(6) NOT NULL,
    expires_at timestamptz NOT NULL,
    used       smallint DEFAULT 0,
    created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user ON password_reset_tokens (user_id);


-- ============================================================================
-- Views: cálculo pesado (GMD, fluxo de caixa, P&L, ocupação) delegado ao banco.
-- ============================================================================

CREATE OR REPLACE VIEW v_gmd_analitico AS
WITH pesagens_ordenadas AS (
    SELECT animal_id, data_pesagem, peso,
        ROW_NUMBER() OVER (PARTITION BY animal_id ORDER BY data_pesagem ASC)  AS rn_asc,
        ROW_NUMBER() OVER (PARTITION BY animal_id ORDER BY data_pesagem DESC) AS rn_desc
    FROM pesagens
    WHERE deleted_at IS NULL
),
primeira_ultima AS (
    SELECT animal_id,
        MAX(data_pesagem) FILTER (WHERE rn_asc  = 1) AS data_inicial,
        MAX(peso)         FILTER (WHERE rn_asc  = 1) AS peso_inicial,
        MAX(data_pesagem) FILTER (WHERE rn_desc = 1) AS data_final,
        MAX(peso)         FILTER (WHERE rn_desc = 1) AS peso_final
    FROM pesagens_ordenadas
    GROUP BY animal_id
)
SELECT
    a.user_id, a.id AS animal_id, a.brinco,
    p.peso_final,
    (p.peso_final - p.peso_inicial) AS ganho_total,
    (p.data_final - p.data_inicial) AS dias,
    -- gmd NULL para animal com pesagens só na mesma data (idêntico ao cálculo
    -- inline que as consultas de rebanho/painel faziam antes do #115).
    CASE WHEN (p.data_final - p.data_inicial) > 0
         THEN (p.peso_final - p.peso_inicial) / (p.data_final - p.data_inicial)
         END AS gmd
FROM primeira_ultima p
JOIN animais a ON p.animal_id = a.id
WHERE a.deleted_at IS NULL;

CREATE OR REPLACE VIEW v_fluxo_caixa AS
SELECT user_id, ano,
       SUM(receita)         AS total_entradas,
       SUM(despesa_compra)  AS total_compras,
       SUM(despesa_med)     AS total_med,
       SUM(despesa_ops)     AS total_ops
FROM (
    SELECT user_id, EXTRACT(YEAR FROM data_venda)::int AS ano,
           preco_venda AS receita, 0 AS despesa_compra, 0 AS despesa_med, 0 AS despesa_ops
    FROM animais
    WHERE data_venda IS NOT NULL AND deleted_at IS NULL
    UNION ALL
    SELECT user_id, EXTRACT(YEAR FROM data_compra)::int,
           0, preco_compra, 0, 0
    FROM animais
    WHERE deleted_at IS NULL AND data_compra IS NOT NULL
    UNION ALL
    SELECT a.user_id, EXTRACT(YEAR FROM m.data_aplicacao)::int,
           0, 0, m.custo, 0
    FROM medicacoes m
    JOIN animais a ON m.animal_id = a.id
    WHERE m.deleted_at IS NULL AND a.deleted_at IS NULL
    UNION ALL
    SELECT user_id, EXTRACT(YEAR FROM data_custo)::int,
           0, 0, 0, valor
    FROM custos_operacionais
    WHERE deleted_at IS NULL
) uniao_geral
GROUP BY user_id, ano;

CREATE OR REPLACE VIEW vw_resultado_lote AS
SELECT
    l.id AS lote_id, l.user_id, l.codigo_lote, l.descricao, l.data_aquisicao,
    COUNT(a.id) AS total_animais,
    COALESCE(SUM(a.preco_compra), 0) AS custo_aquisicao,
    COALESCE(SUM(a.preco_venda) FILTER (WHERE a.data_venda IS NOT NULL), 0) AS receita_vendas,
    COALESCE(SUM(med.custo_med), 0) AS custo_medicacoes,
    COUNT(*) FILTER (WHERE a.data_venda IS NOT NULL) AS animais_vendidos,
    (COALESCE(SUM(a.preco_venda) FILTER (WHERE a.data_venda IS NOT NULL), 0)
     - COALESCE(SUM(a.preco_compra), 0)
     - COALESCE(SUM(med.custo_med), 0)) AS margem_bruta
FROM lotes l
JOIN animais a ON a.lote_id = l.id AND a.deleted_at IS NULL
LEFT JOIN (
    SELECT animal_id, SUM(custo) AS custo_med
    FROM medicacoes WHERE deleted_at IS NULL
    GROUP BY animal_id
) med ON med.animal_id = a.id
WHERE l.deleted_at IS NULL
GROUP BY l.id, l.user_id, l.codigo_lote, l.descricao, l.data_aquisicao;

CREATE OR REPLACE VIEW vw_saldo_estoque AS
SELECT
    p.id AS produto_id, p.user_id, p.nome, p.unidade, p.categoria, p.estoque_minimo,
    COALESCE(SUM(CASE WHEN m.tipo = 'entrada' THEN m.quantidade ELSE 0 END), 0) AS total_entradas,
    COALESCE(SUM(CASE WHEN m.tipo = 'saida'   THEN m.quantidade ELSE 0 END), 0) AS total_saidas,
    COALESCE(SUM(CASE WHEN m.tipo = 'entrada' THEN m.quantidade ELSE -m.quantidade END), 0) AS saldo_atual,
    CASE WHEN COALESCE(SUM(CASE WHEN m.tipo = 'entrada' THEN m.quantidade ELSE -m.quantidade END), 0)
              < p.estoque_minimo THEN 1 ELSE 0 END AS abaixo_minimo,
    MIN(m.data_validade) FILTER (WHERE m.tipo = 'entrada' AND m.data_validade IS NOT NULL) AS proxima_validade,
    CASE WHEN MIN(m.data_validade) FILTER (WHERE m.tipo = 'entrada' AND m.data_validade IS NOT NULL)
              < CURRENT_DATE THEN 1 ELSE 0 END AS tem_vencido
FROM estoque_produtos p
LEFT JOIN estoque_movimentacoes m ON m.produto_id = p.id
GROUP BY p.id, p.user_id, p.nome, p.unidade, p.categoria, p.estoque_minimo;

CREATE OR REPLACE VIEW vw_ocupacao_atual AS
SELECT
    m.id AS modulo_id, m.pasto_id, m.user_id, m.nome AS modulo_nome, m.capacidade_ua,
    o.id AS ocupacao_id, o.data_entrada,
    COUNT(oa.animal_id) AS ua_atual,
    ROUND(COUNT(oa.animal_id) / NULLIF(m.capacidade_ua, 0) * 100, 1) AS pct_lotacao
FROM modulos m
JOIN ocupacoes o ON o.modulo_id = m.id AND o.data_saida IS NULL
JOIN ocupacao_animais oa ON oa.ocupacao_id = o.id
GROUP BY m.id, m.pasto_id, m.user_id, m.nome, m.capacidade_ua, o.id, o.data_entrada;

CREATE OR REPLACE VIEW vw_dias_descanso AS
SELECT
    m.id AS modulo_id, m.pasto_id, m.user_id, m.nome AS modulo_nome,
    MAX(o.data_saida) AS ultima_saida,
    (CURRENT_DATE - MAX(o.data_saida)) AS dias_descanso
FROM modulos m
LEFT JOIN ocupacoes o ON o.modulo_id = m.id AND o.data_saida IS NOT NULL
WHERE m.id NOT IN (SELECT modulo_id FROM ocupacoes WHERE data_saida IS NULL)
GROUP BY m.id, m.pasto_id, m.user_id, m.nome;

CREATE OR REPLACE VIEW vw_gmd_por_modulo AS
WITH oa_rel AS (
    SELECT o.modulo_id, m.nome AS modulo_nome, m.pasto_id, m.user_id, oa.animal_id
    FROM ocupacoes o
    JOIN ocupacao_animais oa ON oa.ocupacao_id = o.id
    JOIN modulos m ON m.id = o.modulo_id
),
po AS (
    SELECT p.animal_id, p.data_pesagem, p.peso,
        ROW_NUMBER() OVER (PARTITION BY p.animal_id ORDER BY p.data_pesagem ASC)  AS rn_asc,
        ROW_NUMBER() OVER (PARTITION BY p.animal_id ORDER BY p.data_pesagem DESC) AS rn_desc
    FROM pesagens p
    JOIN oa_rel r ON r.animal_id = p.animal_id
    WHERE p.deleted_at IS NULL
),
pu AS (
    SELECT animal_id,
        MAX(data_pesagem) FILTER (WHERE rn_asc  = 1) AS data_ini,
        MAX(peso)         FILTER (WHERE rn_asc  = 1) AS peso_ini,
        MAX(data_pesagem) FILTER (WHERE rn_desc = 1) AS data_fim,
        MAX(peso)         FILTER (WHERE rn_desc = 1) AS peso_fim
    FROM po GROUP BY animal_id
),
gmd_calc AS (
    SELECT animal_id,
        CASE WHEN (data_fim - data_ini) > 0
             THEN (peso_fim - peso_ini) / (data_fim - data_ini)
             ELSE NULL END AS gmd
    FROM pu WHERE data_ini <> data_fim
)
SELECT
    r.modulo_id, r.modulo_nome, r.pasto_id, r.user_id,
    COUNT(DISTINCT r.animal_id) AS qtd_animais,
    ROUND(AVG(g.gmd), 3) AS gmd_medio
FROM oa_rel r
LEFT JOIN gmd_calc g ON g.animal_id = r.animal_id
GROUP BY r.modulo_id, r.modulo_nome, r.pasto_id, r.user_id;

CREATE OR REPLACE VIEW vw_historico_vaca AS
SELECT
    r.vaca_id, a.user_id,
    COUNT(*) AS total_coberturas,
    SUM(CASE WHEN r.resultado = 'vivo' THEN 1 ELSE 0 END) AS partos_vivos,
    ROUND(SUM(CASE WHEN r.resultado = 'vivo' THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100, 1) AS taxa_sucesso,
    MIN(r.data_cobertura) AS primeira_cobertura,
    MAX(r.data_cobertura) AS ultima_cobertura
FROM reproducao r
JOIN animais a ON r.vaca_id = a.id
GROUP BY r.vaca_id, a.user_id;

CREATE OR REPLACE VIEW vw_partos_previstos AS
SELECT
    r.id, r.user_id, r.vaca_id,
    v.brinco AS vaca_brinco,
    r.data_cobertura,
    r.data_parto_prevista,
    r.diagnostico,
    (r.data_parto_prevista - CURRENT_DATE) AS dias_restantes
FROM reproducao r
JOIN animais v ON r.vaca_id = v.id AND v.deleted_at IS NULL
WHERE r.diagnostico = 'positivo'
  AND r.data_parto IS NULL
  AND r.data_parto_prevista IS NOT NULL;
